export const queueTable = {
  classQueue: {
    name: "class",
    type: "c!p!t!w",
    pre: ["touch soul", "stand"],
    post: [],
    exclusions: ["fullQueue"],
  },
  freeQueue: {
    name: "free",
    type: "free",
    pre: ["touch soul", "stand"],
    post: [],
    exclusions: ["fullQueue", "shieldQueue"],
  },
  fullQueue: {
    name: "full",
    type: "ebc!w!p!t",
    pre: ["touch soul", "stand"],
    post: [],
    exclusions: ["freeQueue", "shieldQueue", "classQueue"],
  },
  shieldQueue: {
    name: "shield",
    type: "eb!w!t",
    pre: ["touch soul", "stand"],
    post: [],
    exclusions: ["freeQueue", "fullQueue"],
  },
  shipQueue: {
    name: "ship",
    type: "s!w!t",
    pre: ["touch soul", "stand"],
    post: [],
    exclusions: [],
  },
  bloodcloakQueue: {
    name: "bloodcloak",
    type: "!teb",
    pre: ["touch soul"],
    post: [],
    exclusions: ["fullQueue", "freeQueue"],
  },
  battlerageQueue: {
    name: "battlerage",
    type: "!p!t!wu",
    pre: ["touch soul"],
    post: [],
    exclusions: [],
  },
  stunQueue: {
    name: "stun",
    type: "!t",
    pre: ["touch soul"],
    post: [],
    exclusions: [],
  },
};
