const affs = {
  list: [
    "addiction",
    "aeon",
    "agoraphobia",
    "airfisted",
    "amnesia",
    "anorexia",
    "asphyxiating" /**/,
    "asthma",
    "blackout",
    "bleeding",
    "blindness",
    "blistered" /**/,
    "bloodfire" /**/,
    "bound",
    "brokenleftarm",
    "brokenrightarm",
    "brokenleftleg",
    "brokenrightleg",
    "bruisedribs",
    "burning",
    "cadmuscurse",
    "calcifiedskull",
    "calcifiedtorso",
    "claustrophobia",
    "clumsiness",
    "coldfate" /**/,
    "concussion" /**/,
    "conflagration",
    "confusion",
    "corruption",
    "crackedribs",
    "cremated" /**/,
    "crushedthroat" /**/,
    "daeggerimpale",
    "damagedhead",
    "damagedleftarm",
    "damagedleftleg",
    "damagedrightarm",
    "damagedrightleg",
    "darkshade",
    "dazed",
    "dazzled" /**/,
    "deadening",
    "deafness",
    "death",
    "deepsleep" /**/,
    "degenerate" /**/,
    "dehydrated",
    "dementia",
    "demonstain",
    "depression" /**/,
    "deteriorate" /**/,
    "disloyalty",
    "disrupted",
    "dissonance",
    "dizziness",
    "enlightenment",
    "enmesh",
    "ensorcelled" /* pariah */,
    "entangled",
    "epilepsy",
    "fear",
    "flamefisted",
    "flushings" /* pariah */,
    "frozen",
    "generosity",
    "grievouswounds" /**/,
    "guilt" /**/,
    "hamstrung",
    "haemophilia",
    "hallucinations",
    "hatred" /**/,
    "healthleech",
    "heartseed",
    "hecatecurse",
    "hellsight",
    "hindered" /**/,
    "homunculusmercury",
    "horror" /**/,
    "hypersomnia",
    "hypochondria",
    "hypothermia",
    "icefisted",
    "impaled",
    "impatience",
    "indifference" /**/,
    "inquisition",
    "insomnia",
    "internalbleeding",
    // 'insulation', // CUSTOM not an aff
    "isolation" /**/,
    "itching",
    "justice",
    "kaisurge" /**/,
    "kkractlebrand" /**/,
    "laceratedthroat",
    "lapsingconsciousness" /**/,
    "latched" /**/,
    "lethargy",
    "lightbind" /**/,
    "loneliness",
    "lovers",
    "lullaby",
    "manaleech",
    "masochism",
    "mildtrauma",
    "mangledleftarm",
    "mangledleftleg",
    "mangledrightarm",
    "mangledrightleg",
    "mangledhead",
    "mindclamp" /**/,
    "mindravaged" /**/,
    "muddled" /**/,
    "mycalium" /* pariah */,
    "nausea",
    "numbedleftarm",
    "numbedrightarm",
    "pacified",
    "palpatarfeed",
    "paralysis",
    "paranoia",
    "parasite" /* */,
    "peace",
    "penitence" /**/,
    "petrified" /**/,
    "phlogisticated",
    "pinshot",
    "pressure" /**/,
    "prone",
    "pyramides" /* pariah */,
    "pyre" /**/,
    "rebbies" /* pariah */,
    "recklessness",
    "retribution" /**/,
    "revealed" /**/,
    "sandfever" /* pariah */,
    "scalded",
    "scrambledbrains" /**/,
    "scytherus",
    "selarnia",
    "sensitivity",
    "serioustrauma",
    "shadowmadness" /**/,
    "shivering",
    "shyness",
    "silenced" /**/,
    "silver" /**/,
    "skullfractures",
    "slashedthroat",
    "sleeping",
    "slickness",
    "slimeobscure",
    "solarburn" /**/,
    "spiritburn" /**/,
    /* 'spiritdisrupt',*/
    "stun",
    "stupidity",
    "stuttering",
    "temperedcholeric",
    "temperedmelancholic",
    "temperedphlegmatic",
    "temperedsanguine",
    "tenderskin" /**/,
    "tension" /**/,
    "timeflux",
    "timeloop" /**/,
    "tonguetied" /**/,
    "torntendons",
    "transfixation",
    "trueblind",
    "unweavingbody" /**/,
    "unweavingmind" /**/,
    "unweavingspirit" /**/,
    "vertigo",
    "vinewreathed",
    "vitiated" /**/,
    "vitrified" /**/,
    "voidfisted",
    "voyria",
    "waterbonds" /**/,
    /* 'waterdisrupt',*/
    "weakenedmind",
    "weariness",
    "webbed",
    "whisperingmadness",
    "wristfractures",
    "unconsciousness",

    "harmonic",
    "bop",
    "spiritwrack",
    "bedevil",
    "loki",
    "moon",
    "evileye",
    "dragoncurse",
    "swiftcurse",
  ],
  prios: {
    // affs that don't have serverside prio because can't be 'cured', set as 0
    airfisted: 0,
    asphyxiating: 0,
    blistered: 0,
    bloodfire: 0,
    bruisedribs: 0,
    cadmuscurse: 0,
    coldfate: 0,
    conflagration: 0,
    corruption: 0,
    cremated: 0,
    death: 0,
    degenerate: 0,
    dehydrated: 0,
    demonstain: 0,
    deteriorate: 0,
    enlightenment: 0,
    enmesh: 0,
    ensorcelled: 0,
    flamefisted: 0,
    hamstrung: 0,
    hatred: 0,
    hecatecurse: 0,
    hindered: 0,
    homunculusmercury: 0,
    icefisted: 0,
    internalbleeding: 0,
    inquisition: 0,
    lightbind: 0,
    lullaby: 0,
    muddled: 0,
    numbedleftarm: 0,
    numbedrightarm: 0,
    palpatarfeed: 0,
    phlogisticated: 0,
    pinshot: 0,
    slimeobscure: 0,
    stun: 0,
    timeflux: 0,
    trueblind: 0,
    vinewreathed: 0,
    voidfisted: 0,
    weakenedmind: 0,
    unconsciousness: 0,

    // serverside affs 1-26, 26=ignore

    aeon: 2,
    concussion: 2,
    anorexia: 2,
    sleeping: 2,

    heartseed: 3,
    paralysis: 3,
    guilt: 3,
    skullfractures: 3,

    hypothermia: 4,
    impatience: 4,
    torntendons: 4,

    pyramides: 5,
    mycalium: 5,
    flushings: 5,
    rebbies: 5,
    parasite: 5,
    sandfever: 5,
    hypochondria: 5,
    lovers: 5,
    itching: 5,
    pacified: 5,
    peace: 5,
    scytherus: 5,

    asthma: 6,
    bound: 6,
    daeggerimpale: 6,
    clumsiness: 6,
    entangled: 6,
    impaled: 6,
    sensitivity: 6,
    transfixation: 6,
    weariness: 6,
    webbed: 6,

    damagedleftleg: 7,
    damagedrightleg: 7,
    darkshade: 7,
    mangledleftleg: 7,
    mangledrightleg: 7,

    brokenleftleg: 8,
    brokenrightleg: 8,
    confusion: 8,
    hallucinations: 8,
    hypersomnia: 8,

    disrupted: 9,
    mangledhead: 9,
    prone: 9,
    stupidity: 9,
    voyria: 9,

    airdisrupt: 10,
    brokenleftarm: 10,
    brokenrightarm: 10,
    slickness: 10,
    waterdisrupt: 10,
    wristfractures: 10,

    indifference: 11,
    retribution: 11,
    shadowmadness: 11,
    addiction: 11,
    crackedribs: 11,
    haemophilia: 11,
    lethargy: 11,
    nausea: 11,
    whisperingmadness: 11,

    damagedhead: 12,
    hellsight: 12,
    recklessness: 12,

    damagedleftarm: 13,
    damagedrightarm: 13,
    healthleech: 13,
    manaleech: 13,
    temperedcholeric: 13,
    temperedmelancholic: 13,
    temperedphlegmatic: 13,
    temperedsanguine: 13,

    disloyalty: 14,
    dissonance: 14,
    dizziness: 14,
    mangledleftarm: 14,
    mangledrightarm: 14,
    shyness: 14,

    agoraphobia: 15,
    claustrophobia: 15,
    deadening: 15,
    frozen: 15,
    generosity: 15,
    justice: 15,
    loneliness: 15,
    shivering: 15,
    vertigo: 15,

    dementia: 16,
    mildtrauma: 16,
    paranoia: 16,
    serioustrauma: 16,

    epilepsy: 17,

    burning: 18,
    laceratedthroat: 18,
    slashedthroat: 18,
    stuttering: 18,

    selarnia: 19,

    fear: 20,
    masochism: 20,
    scalded: 20,
    dazed: 20,

    // affs you can cure on your own, but no serverside, 30-49, 30=ignore
    bleeding: 30,
    amnesia: 30,
    blackout: 30,

    // def affs
    insomnia: 10,
    // insulation: 20,  // CUSTOM not an aff
    deafness: 21,
    blindness: 22,

    // unknowns, 100=ignore
    harmonic: 100,
    bop: 100,
    spiritwrack: 100,
    bedevil: 100,
    loki: 100,
    moon: 100,
    evileye: 100,
    dragoncurse: 100,
    swiftcurse: 100,
  },
  types: {
    defs: {
      blindness: true,
      deafness: true,
      insomnia: true,
      // insulation: true  // CUSTOM not an aff
    },
    countable: {
      bleeding: { min: 0, max: 15000 },
      burning: { min: 0, max: 5 },
      crackedribs: { min: 0, max: 7 },
      horror: { min: 0, max: 7 },
      skullfractures: { min: 0, max: 7 },
      temperedcholeric: { min: 0, max: 8 },
      temperedmelancholic: { min: 0, max: 8 },
      temperedphlegmatic: { min: 0, max: 8 },
      temperedsanguine: { min: 0, max: 8 },
      torntendons: { min: 0, max: 7 },
      wristfractures: { min: 0, max: 7 },
    },
    timed: {
      aeon: { length: 16 },
      airfisted: { length: 16 },
      blackout: { length: 10 },
      bruisedribs: { length: 30 },
      cadmuscurse: { length: 20 },
      constricted: { length: 30 },
      corruption: { length: 45 },
      dazzled: { length: 60 },
      dehydrated: { length: 60 },
      demonstain: { length: 120 },
      enmesh: { length: 5 },
      ensorcelled: { length: 20 },
      flamefisted: { length: 30 },
      hamstrung: { length: 9 },
      heartseed: { length: 11 },
      hecatecurse: { length: 16 },
      icefisted: { length: 30 },
      internalbleeding: { length: 30 },
      inquisition: { length: 30 },
      lightbind: { length: 22 },
      mudded: { length: 12 },
      numbedleftarm: { length: 7.5 },
      numbedrightarm: { length: 7.5 },
      phlogisticated: { length: 45 },
      pinshot: { length: 18 },
      slimeobscure: { length: 60 },
      stun: { length: 3 },
      timeflux: { length: 60 },
      trueblind: { length: 6 },
      unconsciousness: { length: 10 },
      vinewreathed: { length: 30 },
      voidfisted: { length: 5 },
      weakenedmind: { length: 60 },
    },
    unknown: {
      moon: [
        "stupidity",
        "confusion",
        "epilepsy",
        "masochism",
        "hypersomnia",
        "hallucinations",
      ],
      loki: [
        "stupidity",
        "clumsiness",
        "recklessness",
        "asthma",
        "shyness",
        "darkshade",
        "paralysis",
        "brokenleftarm",
        "brokenrightarm",
        "brokenleftleg",
        "brokenrightleg",
        "sensitivity",
        "disloyalty",
        "nausea",
        "weariness",
        "dizziness",
        "anorexia",
        "voyria",
        "haemophilia",
        "addiction",
        "selarnia",
        "slickness",
        "scytherus",
      ],
      evileye: ["confusion", "dizziness"],
      dragoncurse: [
        "recklessness",
        "clumsiness",
        "epilepsy",
        "dizziness",
        "pacifism",
        "nausea",
        "addiction",
        "anorexia",
        "generosity",
        "disloyalty",
        "sensitivity",
        "vertigo",
        "paranoia",
        "stupidity",
        "hypochondria",
        "lethargy" /* 'insulation'*/,
        "shivering",
        "frozen",
        "impatience",
        "paralysis",
        "asthma",
        "agoraphobia",
      ],
      harmonic: ["stupidity", "recklessness"],
      bop: ["stupidity", "recklessness"],
      swiftcurse: [
        "stupidity",
        "clumsiness",
        "recklessness",
        "asthma",
        "paralysis",
        "deafness",
        "sensitivity",
        "nausea",
        "weariness",
        "dizziness",
        "anorexia",
        "voyria",
        "haemophilia",
        "addiction",
        "impatience",
        "claustrophobia",
        "vertigo",
        "agoraphobia",
        "masochism",
        "epilepsy",
        "manaleech",
        "pacifism",
        "dementia",
        "healthleech",
      ],
      bedevil: ["stupidity", "recklessness"],
    },
    uncurable: {
      bloodfire: true,
      cadmuscurse: true,
      conflagration: true,
      death: true,
      deathsickness: true,
      deepsleep: true,
      enlightenment: true,
      insomnia: true,
      isolation: true,
      lullaby: true,
      mindclamp: true,
      mindisolation: true,
      palpatarfeed: true,
      penitence: true,
      stun: true,
      weakenedmind: true,
    },
  },
};

export { affs as affTable };
