export const mineral_names = [
    'a magnesium chip',
    'an aurum flake',
    'a plumbum flake',
    'a stannum flake',
    'an arsenic pellet',
    'a ferrum flake',
    'an antimony flake',
    'a cuprum flake',
    'an argentum flake',
    'a calamine crystal',
    'a pinch of ground cinnabar',
    'a pinch of realgar crystals',
    'a quartz grain',
    'a pinch of ground malachite',
    'a quicksilver droplet',
    'a potash crystal',
    'a gypsum crystal',
]

export const mineral_names_group = [
    'magnesium chips',
    'aurum flakes',
    'plumbum flakes',
    'stannum flakes',
    'arsenic pellets',
    'ferrum flakes',
    'antimony flakes',
    'cuprum flakes',
    'argentum flakes',
    'calamine crystals',
    'pinches of ground cinnabar',
    'pinches of ground realgar',
    'quartz grains',
    'pinches of ground malachite',
    'quicksilver droplets',
    'potash crystals',
    'gypsum crystals',
]

export const herb_names = [
    'a bloodroot leaf',
    'a piece of kelp',
    'a goldenseal root',
    'some prickly ash bark',
    'some bayberry bark',
    'a ginseng root',
    'a ginger root',
    'a bellwort flower',
    'a lobelia seed',
    'a hawthorn berry',
    'a valerian leaf',
    'a skullcap flower',
    'slippery elm',
    'a kola nut',
    'sileris berry',
    'some irid moss',
    'a black cohosh root',
]

export const herb_names_group = [
    'bloodroot leaves',
    'pieces of kelp',
    'goldenseal roots',
    'pieces of prickly ash bark',
    'pieces of bayberry bark',
    'ginseng roots',
    'ginger roots',
    'bellwort flowers',
    'lobelia seeds',
    'hawthorn berries',
    'valerian leaves',
    'skullcap flowers',
    'slippery elms',
    'kola nuts',
    'sileris berries',
    'pieces of irid moss',
    'cohosh roots',
]

export const herb_name_to_herb = {
    'a magnesium chip': 'magnesium',
    'an aurum flake': 'aurum',
    'a plumbum flake': 'plumbum',
    'a stannum flake': 'stannum',
    'an arsenic pellet': 'arsenic',
    'a ferrum flake': 'ferrum',
    'an antimony flake': 'antimony',
    'a cuprum flake': 'cuprum',
    'an argentum flake': 'argentum',
    'a calamine crystal': 'calamine',
    'a pinch of ground cinnabar': 'cinnabar',
    'a pinch of realgar crystals': 'realgar',
    'a quartz grain': 'quartz',
    'a pinch of ground malachite': 'malachite',
    'a quicksilver droplet': 'quicksilver',
    'a potash crystal': 'potash',
    'a gypsum crystal': 'gypsum',
    'a bloodroot leaf': 'bloodroot',
    'a piece of kelp': 'kelp',
    'a goldenseal root': 'goldenseal',
    'some prickly ash bark': 'ash',
    'some bayberry bark': 'bayberry',
    'a ginseng root': 'ginseng',
    'a ginger root': 'ginger',
    'a bellwort flower': 'bellwort',
    'a lobelia seed': 'lobelia',
    'a hawthorn berry': 'hawthorn',
    'a valerian leaf': 'valerian',
    'a skullcap flower': 'skullcap',
    'slippery elm': 'elm',
    'a kola nut': 'kola',
    'sileris berry': 'sileris',
    'some irid moss': 'moss',
    'a black cohosh root': 'cohosh',
    'magnesium chips': 'magnesium',
    'aurum flakes': 'aurum',
    'plumbum flakes': 'plumbum',
    'stannum flakes': 'stannum',
    'arsenic pellets': 'arsenic',
    'ferrum flakes': 'ferrum',
    'antimony flakes': 'antimony',
    'cuprum flakes': 'cuprum',
    'argentum flakes': 'argentum',
    'calamine crystals': 'calamine',
    'pinches of ground cinnabar': 'cinnabar',
    'pinches of ground realgar': 'realgar',
    'quartz grains': 'quartz',
    'pinches of ground malachite': 'malachite',
    'quicksilver droplets': 'quicksilver',
    'potash crystals': 'potash',
    'gypsum crystals': 'gypsum',
    'bloodroot leaves': 'bloodroot',
    'pieces of kelp': 'kelp',
    'goldenseal roots': 'goldenseal',
    'pieces of prickly ash bark': 'ash',
    'pieces of bayberry bark': 'bayberry',
    'ginseng roots': 'ginseng',
    'ginger roots': 'ginger',
    'bellwort flowers': 'bellwort',
    'lobelia seeds': 'lobelia',
    'hawthorn berries': 'hawthorn',
    'valerian leaves': 'valerian',
    'skullcap flowers': 'skullcap',
    'slippery elms': 'elm',
    'kola nuts': 'kola',
    'sileris berries': 'sileris',
    'pieces of irid moss': 'moss',
    'cohosh roots': 'cohosh',
}

export const cacheTable = {
    magnesium: 0,
    plumbum: 0,
    arsenic: 0,
    potash: 0,
    stannum: 0,
    malachite: 0,
    realgar: 0,
    cinnabar: 0,
    antimony: 0,
    ferrum: 0,
    quartz: 0,
    quicksilver: 0,
    aurum: 0,
    calamine: 0,
    cuprum: 0,
    argentum: 0,
    gypsum: 0,

    // herbs
    ginseng: 0,
    bloodroot: 0,
    kelp: 0,
    hawthorn: 0,
    lobelia: 0,
    bellwort: 0,
    ginger: 0,
    bayberry: 0,
    ash: 0,
    goldenseal: 0,
    moss: 0,
    valerian: 0,
    elm: 0,
    skullcap: 0,
    sileris: 0,
    kola: 0,
    cohosh: 0,
}
