export const limbs = {
    short: {
        rl: 'right leg',
        ll: 'left leg',
        ra: 'right arm',
        la: 'left arm',
        h: 'head',
        tt: 'torso',
        c: 'centre',
        l: 'left',
        r: 'right',
    },
    long: {
        'right leg': 'rl',
        'left leg': 'll',
        'right arm': 'ra',
        'left arm': 'la',
        head: 'h',
        torso: 'tt',
        centre: 'c',
        left: 'l',
        right: 'r',
    },
}

export const dirs = [
    'e',
    'w',
    's',
    'n',
    'ne',
    'se',
    'sw',
    'nw',
    'in',
    'out',
    'd',
    'u',
]

export const dirMap = {
    e: 'east',
    w: 'west',
    s: 'south',
    n: 'north',
    ne: 'northeast',
    se: 'southeast',
    sw: 'southwest',
    nw: 'northwest',
    in: 'in',
    out: 'out',
    down: 'down',
    d: 'down',
    u: 'up',
    up: 'up',
}

export const oppDirs = {
    e: 'west',
    w: 'east',
    s: 'north',
    n: 'south',
    ne: 'southwest',
    se: 'northwest',
    sw: 'northeast',
    nw: 'southeast',
    in: 'out',
    out: 'in',
    down: 'up',
    d: 'up',
    u: 'down',
    up: 'down',
}

export const shortDirs = {
    east: 'e',
    west: 'w',
    south: 's',
    north: 'n',
    northeast: 'ne',
    northwest: 'nw',
    southeast: 'se',
    southwest: 'sw',
    in: 'in',
    out: 'out',
    down: 'd',
    up: 'up',
}
