export const EVENT_TYPES = {
  SYSTEM_SETTINGS_UPDATE: "SYSTEM/SETTINGS_UPDATE",
  SYSTEM_STATUS_SET: "SYSTEM/STATUS_SET",
  SYSTEM_PAUSE: "SYSTEM/PAUSE",
  SYSTEM_UNPAUSE: "SYSTEM/UNPAUSE",
  SYSTEM_TARGET_SET: "SYSTEM/TARGET_SET",

  CHAR_VITALS: "CHAR/VITALS",
  CHAR_STATUS: "CHAR/STATUS",

  AFF_LIST: "AFF/LIST",
  AFF_GOT: "AFF/GOT",
  AFF_LOST: "AFF/LOST",
  AFF_COUNT_SET: "AFF/COUNT_SET",
  AFF_COUNT_ADD: "AFF/COUNT_ADD",
  AFF_COUNT_SUB: "AFF/COUNT_SUB",
  AFF_PRIO_SET: "AFF/PRIO_SET",

  DEF_LIST: "DEF/LIST",
  DEF_GOT: "DEF/GOT",
  DEF_LOST: "DEF/LOST",
  DEF_PRIO_SET: "DEF/PRIO_SET",

  BAL_GOT: "BAL/GOT",
  BAL_LOST: "BAL/LOST",

  CACHE_COUNT_ADD: "CACHE/COUNT_ADD",
  CACHE_COUNT_SUB: "CACHE/COUNT_SUB",
  CACHE_RIFT_SET: "CACHE/RIFT_SET",

  OUTPUT_ADD_NEXSYS_COMMANDS: "OUTPUT/NEXSYS_ADD_COMMANDS",
  OUTPUT_SENT_NEXSYS: "OUTPUT/NEXSYS_SENT",
  OUTPUT_SENT_PRECACHE: "OUTPUT/PRECACHE_SENT",
  OUTPUT_BLOCKED_NEXSYS: "OUTPUT/NEXSYS_BLOCKED",
  OUTPUT_BLOCKED_PRECACHE: "OUTPUT/PRECACHE_BLOCKED",
  OUTPUT_ACK_NEXSYS: "OUTPUT/NEXSYS_ACK",
  OUTPUT_ACK_PRECACHE: "OUTPUT/PRECACHE_ACK",
  OUTPUT_CLEAR_PENDING_NEXSYS: "OUTPUT/NEXSYS_CLEAR_PENDING",
  OUTPUT_CLEAR_PENDING_PRECACHE: "OUTPUT/PRECACHE_CLEAR_PENDING",
  OUTPUT_CLEAR_PENDING_SERVERSIDE: "OUTPUT/SERVERSIDE_CLEAR_PENDING",

  SERVERSIDE_STATUS_SNAPSHOT: "SERVERSIDE/STATUS_SNAPSHOT",
  SERVERSIDE_AFF_SNAPSHOT: "SERVERSIDE/AFF_SNAPSHOT",
  SERVERSIDE_DEF_SNAPSHOT: "SERVERSIDE/DEF_SNAPSHOT",
  SERVERSIDE_DESIRED_UPDATE: "SERVERSIDE/DESIRED_UPDATE",
  SERVERSIDE_LOADED: "SERVERSIDE/LOADED",

  QUEUE_ADD: "QUEUE/ADD",
  QUEUE_PREPEND: "QUEUE/PREPEND",
  QUEUE_CLEAR: "QUEUE/CLEAR",
  QUEUE_CLEAR_ALL: "QUEUE/CLEAR_ALL",
  QUEUE_SENT: "QUEUE/SENT",
  QUEUE_FIRED: "QUEUE/FIRED",
};
