const talismans = {
    wonders: {
        baitbucket: {
            name: "a banrcle-cruest bucket",
            brief: "This special bucket will automatically generate bait every Achaean day.",
            buckethandle: {count: 0, redeem: 10, complete: 15},
            bucketleft: {count: 0, redeem: 10, complete: 15},
            bucketright: {count: 0, redeem: 10, complete: 15},
            bucketwater: {count: 0, redeem: 10, complete: 15}
        },
        dragonskinpack: {},
        paltinumwhistle: {},
        ramshorn: {},
        monocle: {},
        globe: {},
    },
    miscellaneous: {},
    historical: {},
    conclave: {},
    marks: {},
    seafaring: {},
    death: {},
    blackwave: {},
    races: {},
    cities: {},
    monks: {},
    elemental: {},
    yggdrasil: {},
    contenders: {},
    underworld: {},
    renegades: {},
    invasion: {},
    war: {},
    planes: {},
    eldergods: {},
}